# Workflow to build and release OcrInspector for production
name: Publish Services

on:
  workflow_run:
    workflows:
      - Test Services
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4